name: Tunnels-Common
main: com.caved_in.commons.Commons
version: 1.0
description: Commons Library built for easier plugin development
author: Brandon
depend: [PopupMenuAPI]
softdepend: [TagAPI]
commands:
   buypremium:
      description: Used to add premium (Console only)
      usage: /<command> <PlayerName>
   removepremium:
      description: Used to remove premium (Console only)
      usage: /<command> <PlayerName>
   ban:
      description: Used to ban a player across all servers
      usage: /<command> <Player> <Reason> [t:Time]
   unban:
      description: Used to unban a player across all servers
      usage: /<command> <name>
   pardon:
      description: Used to unban a player across all servers
      usage: /<command> <name>
   mute:
      description: Used to mute a player across all servers
      usage: /<command> <Player>
   unmute:
      description: Used to unmute a player across all servers
      usage: /<command> <Player>
   buyinfo:
      usage: /buyinfo <player>
   msg:
      usage: /msg <player> <message>
      aliases: [m, t, tell, whisper]
   ci:
      usage: /<command> [player]
      aliases: [clearinventory, clearinv]
   tphere:
      usage: /<command> <player>
      aliases: [bring]
   tp:
      usage: /<command> <player> [Player]
      aliases: [teleport]
   fly:
      usage: /fly
   fw:
      usage: /fw
   hat:
      usage: /msg <player>
   gm:
      usage: /gm [Mode]
   maintenance:
      usage: /maintenance [on/off/toggle]
   silence:
      usage: /silence
   unsilence:
      usage: /unsilence
   nick:
      usage: /nick help
   nicklist:
      usage: /nicklist
   friends:
      usage: /friends <SubCommand>
   r:
      usage: /<command> <Message>
   skull:
      usage: /<command> <Name>
   setspawn:
      usage: /setspawn
   xp:
      usage: /<command>
   more:
      usage: /<command>
   addcurrency:
      usage: /<command> <Player> <Amount>
   heal:
      usage: /<command>
